<div class="alert alert-info">
<h1><center><font color=darkblue>TÌM MA TRẬN NGHỊCH ĐẢO BẰNG GAUSS JORDAN<font></center></h1>


</div>

### <font color=RoyalBlue>Import các thư viện cần thiết:<font>
- Numpy để làm việc với mảng
- Pandas để làm việc với file dạng csv hoặc xlsx

In [1]:
import numpy as np
import pandas as pd

### <font color=RoyalBlue>Đọc file nghichdao.xlsx <font>
và đưa về dạng mảng

In [2]:
df = pd.read_excel('nghichdao.xlsx', header = None)
df

0    1   2
0  50  107  36
1  25   54  20
2  31   66  21

In [3]:
matrix = df.to_numpy()
print(matrix)

[[ 50 107  36]
 [ 25  54  20]
 [ 31  66  21]]


### <font color=RoyalBlue>Khởi tạo một số mảng phụ lưu kết quả <font>
- index_row: lưu các hàng của phần tử giải
- index_column: lưu các cột của phần tử giải
- matrixE: ma trận đơn vị có kích thước n.n
- Biến n: lưu kích thước của ma trận

In [4]:
n = len(matrix)
print(n)

3


In [5]:
index_row = []  
index_column = []  

In [6]:
matrixE = np.zeros([n,n])
for i in range(n):
    matrixE[i,i] = 1.0

### <font color=RoyalBlue>Khởi tạo hàm tìm phần tử giải <font>
<br>Thuật toán:<br/>
- B1: tạo biến pivot_element (phần tử giải), mảng index_temp (mảng cho phần tử có trị tuyệt đối lớn nhất trong hàng.
- B2: Cho row chạy tới len(matrix) (kích thước của ma trận $A$)
- B3: Kiểm tra nếu hàng này đã có phần tử giải thì bỏ qua
- B4: Tìm phần tử có trị tuyệt đối lớn nhất trong hàng
- B5: Nếu trong hàng có chứ $1$ hoặc $-1$ chuyển sang bước 6, trái lại chuyển sang bước 9
- B6: Chọn làm phần tử giải luôn (gán vào biến pivot_element) và gán row_pivot_element = row
- B7: Liệt kê các phần tử có giá trị bằng với giá trị tuyệt đối của pivot_element vào mảng index_temp
- B8: Gán lại index_temp là phần tử đầu tiên trong mảng, chuyển tới bước 10
- B9: Nếu max_row > pivot_element thì gán pivot_element = max_row, chuyển sang bước 7
- B10: Nếu pivot_element $\neq$ 0 thì thêm row_pivot_element vào mảng index_row, index_temp vào mảng index_column
-B11: Ngoài ra nếu pivot_element $\neq$ 0 thì biến gán vào biến w = 1, trái lại thì là -1.

In [7]:
def find_pivot_element():
    global index_row, index_column, w
    index_temp = []
    pivot_element = 0
    for row in range(0, len(matrix)):
        if row in index_row:  # Bỏ qua vì hàng này đã có phần tử giải
            continue
        max_row = np.amax(abs(matrix[row, 0:(len(matrix[0]))]))  # Tìm phần tử lớn nhất trong hàng row
        if (1 in matrix[row, 0:(len(matrix[0]))]) or (
                -1 in matrix[row, 0:(len(matrix[0]))]):  # Nếu có 1 hoặc -1 trong hàng row => chọn làm phần tử giải
            pivot_element = 1
            row_pivot_element = row
            index_temp = np.where(abs(matrix[row, 0:(len(matrix[0]))]) == pivot_element)
            index_temp = index_temp[:1]
            index_temp = index_temp[0][0]
            break
        elif max_row > pivot_element:  # Lưu giá trị phần tử giải, tìm vị trí trên ma trận
            pivot_element = max_row
            row_pivot_element = row
            index_temp = np.where(abs(matrix[row, 0:(len(matrix[0]))]) ==pivot_element)
            index_temp = index_temp[:1]
            index_temp = index_temp[0][0]
    if pivot_element != 0: # Lưu vị trí hàng và cột của phần tử giải
        w = 1
        index_row.append(row_pivot_element)
        index_column.append(int(index_temp))
    else:
        w = -1
        print("Ma trận không khả nghịch!!!!")
#         quit()

### <font color=RoyalBlue>Khởi tạo hàm biến đổi ma trận theo pp Gauss Jordan <font>
<br>Thuật toán:<br/>
- B1: Thực hiện gói tìm phần tử giải
- B2: Tạo ma trận không có kích thước đúng bằng ma trận A
- B3: Duyệt các dòng, mỗi dòng thực hiện các bước đằng sau
- B4: Gán m là $-\frac{\alpha_{iq}}{\alpha_{pq}}$
- B5: Nhân vào với $\alpha_{pj}$ và lưu vào 2 ma trận không là zeros_array và z
- B6: Sau khi lưu hết thì cộng zeros_array với ma trận gốc, z cộng với ma trận đơn vị

In [11]:
def Gauss_Jordan_method():
    global matrix,matrixE
    find_pivot_element()
    zeros_array = np.zeros([n,n])  # Tạo 1 ma trận không
    z = np.zeros([n,n])  # Tạo 1 ma trận không
    for row in range(0, len(matrix)):
        if row == index_row[-1]:
            continue
        m = - matrix[row][index_column[-1]] / matrix[index_row[-1]][index_column[-1]] #Tìm m
        zeros_array[row] = matrix[index_row[-1]] * m
        z[row] = matrixE[index_row[-1]] * m
    matrix = matrix + zeros_array
    matrixE = matrixE+z

### <font color=RoyalBlue>Hàm chuẩn hóa hệ số của phần tử giải <font>
Để chia hệ số của phần tử giải $=1$

In [9]:
def normalize_pivot_element():
    for i in range(len(index_row)):
        matrixE[index_row[i]] = matrixE[index_row[i]] / matrix[index_row[i]][index_column[i]]
        matrix[index_row[i]] = matrix[index_row[i]] / matrix[index_row[i]][index_column[i]]

### <font color=RoyalBlue>Tạo hàm so sánh nhằm đổi vị trí <font>

In [ ]:
def sosanh(a, b, n):
    check = 0
    for i in range(n):
        if a[i] > b[i]: return 1
        elif a[i] < b[i]: return -1
    return  check

### <font color=RoyalBlue>Chương trình chính <font>
Thực hiện lần lượt các gói Gauss_Jordan_method() (chạy n lần), chuẩn hóa, sau đó in ra ma trận có khả nghịch hay ko; đổi các hàng để chuẩn hóa ma trận và in ra ma trận nghịch đảo.

In [10]:
print("Gauss-Jordan method to find the inversed matrix")
for i in range(0, n):
    Gauss_Jordan_method()
normalize_pivot_element()
print()
if w == -1: exit()
else: 
    for i in range(n):
        for j in range(0, n-i-1):
            if sosanh(matrix[j],matrix[j+1],n) == -1:
                for k in range(n):
                    matrix[j,k], matrix[j+1, k] = matrix[j+1, k], matrix[j, k]
                    matrixE[j, k], matrixE[j + 1, k] = matrixE[j + 1, k], matrixE[j, k]
    print("Ma trận nghịch đảo là:")
    print(matrixE)

Gauss-Jordan method to find the inversed matrix

Ma trận nghịch đảo là:
[[-186.  129.  196.]
 [  95.  -66. -100.]
 [ -24.   17.   25.]]
